apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-blue
  namespace: ecommerce
  labels:
    app: ai-service
    slot: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
      slot: blue
  template:
    metadata:
      labels:
        app: ai-service
        slot: blue
    spec:
      containers:
      - name: ai-service
        image: haadtechacr2026.azurecr.io/ai-service:blue
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: DATABASE_URL
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: GROQ_API_KEY
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: CORE_SERVICE_URL
          value: "http://core-service:3003"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-green
  namespace: ecommerce
  labels:
    app: ai-service
    slot: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ai-service
      slot: green
  template:
    metadata:
      labels:
        app: ai-service
        slot: green
    spec:
      containers:
      - name: ai-service
        image: haadtechacr2026.azurecr.io/ai-service:green
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: DATABASE_URL
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: GROQ_API_KEY
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: CORE_SERVICE_URL
          value: "http://core-service:3003"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: ecommerce
spec:
  selector:
    app: ai-service
    slot: blue
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
